### ISSUE TITLE
I've altered your big button theme . .

### ISSUE THREAD

**Issue by ghost** [smurphos/Window_Borders_Mint_19#3]
. . so as to give it, in its dark variant, a subtle gradient in its focused titlebars. The change makes the theme slightly less flat and by dint of that it is easier to tell windows apart.

I know this isn't really an 'issue', i.e. problem, but I thought I'd let you know that you can have and host the theme if you like. Screenshots:

![image](https://user-images.githubusercontent.com/9998846/47611392-4092a980-da5c-11e8-96a0-87cae0374c43.png)

![image](https://user-images.githubusercontent.com/9998846/47611404-95cebb00-da5c-11e8-8fc0-401a65a2eb8d.png)

![image](https://user-images.githubusercontent.com/9998846/47611422-0e357c00-da5d-11e8-8115-a520688f3cc2.png)

I might add a small amount - or even smaller amount - of shading to unfocused titlebars.

**Comment by smurphos** [comment]
Thanks,

Can do - I'll grab the file from your aborted PR over on the Cinnamon repo.

BTW don't take JosephM's response personally - he's right that for consistency within Mint Y the GTK theme would need to be amended to match for apps that use a header bar rather than the metacity title bar.

The BB versions here are tweaked from Mint 19s original release not 18.3 - I'll update the readme to clarify.
